site_name: GRUPO 6 MDS/EPS

repo_name: 'fga-eps-mds/2020.1-Grupo6'
repo_url: 'https://github.com/fga-eps-mds/2020.1-Grupo6'

nav:
  - Documentação do Projeto: 
    - Sobre: index.md
    - Roadmap: Roadmaps/roadmap.md
    - Documento de Visão: org_artifacts/vision_doc.md
    - Engenharia de Requisitos: org_artifacts/requirements_engineering.md
    - Artefatos Organizacionais:
      - Documento de Gestão e Configuração de Software: org_artifacts/software_configuration_management.md

theme: readthedocs