site_name: Vamos Cuidar - Gestão

repo_name: 'fga-eps-mds/2020.1-Grupo6'
repo_url: 'https://github.com/fga-eps-mds/2020.1-Grupo6'

nav:
  - Documentação do Projeto: 
    - Sobre: index.md
    - Roadmap: Roadmaps/roadmap.md
    - Documento de Visão: org_artifacts/vision_doc.md
    - Engenharia de Requisitos: org_artifacts/requirements_engineering.md
    - Termo de Abertura do Projeto: org_artifacts/tap.md
    - Artefatos Organizacionais:
      - Políticas de Branch: policies/branches.md
      - Políticas de Commit: policies/commits.md
      - Políticas de Pastas e Arquivos: policies/files_and_folders.md
      - Políticas de Issues: policies/issues.md
      - Políticas de Pull Requests: policies/pull_requests.md
    - Sprints:
      - Sprint 0: docs/sprints/sprint0.md
      - Sprint 1: docs/sprints/sprint0.md
      - Sprint 2: docs/sprints/sprint0.md


theme: 
  name: material
  language: 'pt'
  palette:
    primary: 'green'
    accent: 'green'

